name: Deploy Results to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
        
    - name: Install dependencies
      run: |
        cd results
        pnpm install
        
    - name: Build
      env:
        VITE_GROQ_API_KEY: ${{ secrets.VITE_GROQ_API_KEY }}
      run: |
        cd results
        pnpm run build 
        
    - name: Inject API Key into built HTML
      run: |
        cd results/dist
        sed -i 's|<!-- Runtime API key injection point -->|<script>window.GROQ_API_KEY = "${{ secrets.VITE_GROQ_API_KEY }}";</script>|' index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results/dist
